#!/usr/bin/env php
<?php
/*
 * This file is part of the Onion package.
 *
 * (c) Yo-An Lin <cornelius.howl@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 */

require __DIR__ . '/../vendor/pear/Universal/ClassLoader/SplClassLoader.php';
$classLoader = new \Universal\ClassLoader\SplClassLoader(array( 
    'Onion' => 'src',
    'CurlKit' => 'src',
    'CLIFramework' => 'vendor/pear',
    'PEARX' => 'vendor/pear',
    'GetOptionKit' => 'vendor/pear',
));
$classLoader->useIncludePath(true);
$classLoader->register();
$app = \Onion\Application::getInstance();
$app->run( $argv );
