#!/usr/bin/env php
<?php
/*
 * This file is part of the Onion package.
 *
 * (c) Yo-An Lin <cornelius.howl@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 */

require '../Universal/src/Universal/ClassLoader/SplClassLoader.php';
$classLoader = new \Universal\ClassLoader\SplClassLoader(array( 
    'Onion' => 'src',
    'CLIFramework' => 'vendor/pear',
    'GetOptionKit' => 'vendor/pear',
));
$classLoader->useIncludePath(true);
$classLoader->register();

try {
    $app = new \Onion\Application;
    $app->run( $argv );
} 
catch( Exception $e )
{
    die( $e->getMessage() );
}
