#!/usr/bin/env php
<?php
/*
 * This file is part of the Onion package.
 *
 * (c) Yo-An Lin <cornelius.howl@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 */
define('ROOT', dirname(__DIR__) );
require ROOT . '/vendor/pear/Universal/ClassLoader/SplClassLoader.php';
$classLoader = new \Universal\ClassLoader\SplClassLoader(array( 
    'Onion' => ROOT . '/src',
    'CurlKit' => ROOT . '/src',
    'CLIFramework' => ROOT . '/vendor/pear',
    'PEARX' => ROOT . '/vendor/pear',
    'GetOptionKit' =>  ROOT . '/vendor/pear',
));
$classLoader->useIncludePath(true);
$classLoader->register();
$app = \Onion\Application::getInstance();
$app->run( $argv );
